# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'INF_PROJ_2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_INF_PROJ_2DialogBase(object):
    def setupUi(self, INF_PROJ_2DialogBase):
        INF_PROJ_2DialogBase.setObjectName("INF_PROJ_2DialogBase")
        INF_PROJ_2DialogBase.resize(719, 761)
        self.button_box = QtWidgets.QDialogButtonBox(INF_PROJ_2DialogBase)
        self.button_box.setGeometry(QtCore.QRect(340, 710, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.pushButton_zlicz = QtWidgets.QPushButton(INF_PROJ_2DialogBase)
        self.pushButton_zlicz.setGeometry(QtCore.QRect(260, 140, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_zlicz.setFont(font)
        self.pushButton_zlicz.setObjectName("pushButton_zlicz")
        self.label_warstwa = QtWidgets.QLabel(INF_PROJ_2DialogBase)
        self.label_warstwa.setGeometry(QtCore.QRect(230, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_warstwa.setFont(font)
        self.label_warstwa.setObjectName("label_warstwa")
        self.mMapLayerComboBox_warstwa = QgsMapLayerComboBox(INF_PROJ_2DialogBase)
        self.mMapLayerComboBox_warstwa.setGeometry(QtCore.QRect(160, 80, 381, 41))
        self.mMapLayerComboBox_warstwa.setObjectName("mMapLayerComboBox_warstwa")

        self.retranslateUi(INF_PROJ_2DialogBase)
        self.button_box.accepted.connect(INF_PROJ_2DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(INF_PROJ_2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(INF_PROJ_2DialogBase)

    def retranslateUi(self, INF_PROJ_2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        INF_PROJ_2DialogBase.setWindowTitle(_translate("INF_PROJ_2DialogBase", "Geodesy_plug"))
        self.pushButton_zlicz.setText(_translate("INF_PROJ_2DialogBase", "Zlicz"))
        self.label_warstwa.setText(_translate("INF_PROJ_2DialogBase", "Wybierz warstwę:"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    INF_PROJ_2DialogBase = QtWidgets.QDialog()
    ui = Ui_INF_PROJ_2DialogBase()
    ui.setupUi(INF_PROJ_2DialogBase)
    INF_PROJ_2DialogBase.show()
    sys.exit(app.exec_())
